"""Migration initiale

Revision ID: 2aa233ca4241
Revises: 
Create Date: 2024-06-09 18:21:58.973504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa233ca4241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_position'), ['position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_position'))
        batch_op.drop_index(batch_op.f('ix_employee_phone'))
        batch_op.drop_index(batch_op.f('ix_employee_name'))
        batch_op.drop_index(batch_op.f('ix_employee_first_name'))
        batch_op.drop_index(batch_op.f('ix_employee_created_at'))
        batch_op.drop_index(batch_op.f('ix_employee_city'))
        batch_op.drop_index(batch_op.f('ix_employee_address'))

    op.drop_table('employee')
    # ### end Alembic commands ###
